### PR TITLE
Improve formatting of help descriptions

### PR DESCRIPTION
**Pull request by wgahr123**
* new function: cxxopts::Option::set_width(size_t width)
  Set the size of a helpline.
* new function: cxxopts::Option::set_tab_expansion()
  Expand the tabs in descriptions.
  The tabsize 8 chars, base is start of description.
  The descriptions are not disturbed by adding additional options.
* Allow newlines \n nad tabs \t in descriptions.

Other changes (last commit/new commit):
* 1453/1471: size_t for OPTION_LONGEST and OPTION_DESC_GAP.
  This prevents the static cast in 2086/2140.
* 2088/2142: in case of small width the value of
  "width - longest - OPTION_DEC_GAP" becomes negative.
  Because size_t is unsigned the result is a big number, and
  the width of the column of the descriptions is not shortened.
* new 2143: When the given width is too small, it is set to
  longest + OPTION_DESC_GAP + 10
* new 1570: A long description is broken into multiple lines, and
  the iterator lastSpace remembers the begin of the last word.
  But when the iterator current reaches the end of line, the whole
  string from iterator is printed, which in soome cases is too
  long. Thats why one blank is added to the description to trigger
  the handling of lastSpace.
  Accordingly in 1574/1627 the line is shortened by one char.

---
This change is [Reviewable](https://reviewable.io/reviews/jarro2783/cxxopts/215)

### CODE REVIEW

**Comment by wgahr123** [comment]
Im my branch https://github.com/wgahr123/cxxopts/tree/desc-width there is a test program "src/test_desc.cpp". It can be compiled by vc14, clang and gcc7 - see the bat-files "compile-*.bat".  The code in these bat-file should berun without problems in bare linux - I used wsl2/OpenSuse-15.1 in my windows-environment.

**Comment by wgahr123** [comment]
I see there is a signed/unsigned problem. I will look for that soon.

**Comment by jarro2783** [comment]
Thanks, I'll take a look when you can fix up the build failures.

**Comment by wgahr123** [comment]
I tested with clang, gcc7 and vc14 with and without unicode.
I checked the width in the range 1..100.

**Comment by wgahr123** [comment]
#213 could not compile properly with all compilers/Unicode.
Because of that a main loop was rewritten.
Additionally a new feature was added ( tabulator setting).
So #213 was cancelled and its now #215.
Maybe I did something wrong with the PR handling? Its my first one..

**Comment by jarro2783** [comment]
I seem to have missed this. I will try to look at it in more detail soon.

**Comment by danlipsa** [comment]
@jarro2783 I found this PR after searching for this type of functionality in cxxopts. Thank you @wgahr123 for providing it. It would be great if it could be merged. Thanks!

**Comment by jarro2783** [comment]
This PR has been open for far too long. I will take a look at this and get it merged soon.

**Comment by danlipsa** [comment]
@jarro2783 Thanks you! That would be great.

**Comment by jarro2783** [comment]
This code probably all needs some tests, but it looks good for now.

**Comment by wgahr123** [comment]
Jarro, I took a look at the merge and found this bad syntax in my code:

line 1522:
String
    format_description
    (
      const HelpOptionDetails& o,
      size_t start,
      size_t allowed,
      bool m_tab_expansion         <<<  should be "tab_expansion"
    )

line 1547:
   if (m_tab_expansion)               <<< same

I am sorry and I would fix it by PR, but just now I am really busy, pls look at it some time.

Wolfgang

**Comment by wgahr123** [comment]
An example to expand the README.md is in #213.

**Comment by jarro2783** [comment]
Thanks, I fixed it up.

**Pull request merged**
