### PR TITLE
Fix std::isblank assertion error in Visual Studio Chinese Debug

### PR DESCRIPTION
**Pull request by 66maer**
This change is [Reviewable](https://reviewable.io/reviews/jarro2783/cxxopts/365)

### CODE REVIEW

**Comment by 66maer** [comment]
close #365

**Comment by jarro2783** [comment]
Do you mean that this closes #364 ?

**Comment by 66maer** [comment]
oh,sorry...I've already changed it

**Comment by jarro2783** [comment]
This looks fine, thanks.

**Pull request merged**
