### PR TITLE
Derive `option_has_no_value_exception` from `OptionParseException`

### PR DESCRIPTION
**Pull request by MarcoKoch**
Implements #327.

---
This change is [Reviewable](https://reviewable.io/reviews/jarro2783/cxxopts/328)

### CODE REVIEW

**Comment by jarro2783** [comment]
This isn't a parse error, it is a usage error. So there is a reason that the two are separated.

**Comment by MarcoKoch** [comment]
Seems like I had a misunderstanding about what that exception exactly means.

Just to clarify that I understand your reasoning correctly:
I came across this exception when trying to read the value of an optional positional argument, which wasn't supplied by the user. Am I right that I'm supposed to use `ParseResult::count()` to check whether a value is present before trying to read it with `OptionValue::as()`? So there are actually three categories of exceptions:
1. Exceptions from invalid option specifications (`OptionSpecException`)
2. Exceptions from invalid arguments supplied by the user (`OptionParseException`)
3. Exceptions from trying to access the results of a parse in an invalid manner (which `option_has_no_value_exception` falls into)

**Comment by jarro2783** [comment]
Yes that's correct. I think all of those should derive from `OptionException`, so if you want to catch everything in one go you can just catch that instead.

**Comment by MarcoKoch** [comment]
Adding an extra `catch` is fine now I understand the difference. I probably was just a bit confused because the README only mentions two categories of exceptions.
Maybe it would also make sense to add a third base class to reflect the conceptual difference in code, even though `option_has_no_value_exception` would be the only one that derives from it at the moment.
If you are okay with that, I will update my pull request accordingly.

**Pull request closed without merging**
