### PR TITLE
Replace curly single-quotes with a standard quote character.  

### PR DESCRIPTION
**Pull request by petewall**
This fixes an issue with printing those characters on Windows.

---
This change is [Reviewable](https://reviewable.io/reviews/jarro2783/cxxopts/35)

### CODE REVIEW

**Comment by jarro2783** [comment]
As mentioned in #34, I don't want to throw away quotes just because Windows is deficient. I would prefer that single quotes be used only if on a platform that can't handle UTF-8, overridable by the user requesting curly quotes explicitly.

**Comment by jarro2783** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/cxxopts.hpp, line 321 at r1](https://reviewable.io:443/reviews/jarro2783/cxxopts/35#-KZT5eRoHAHNYjsjqVb9:-KZT5eRoHAHNYjsjqVbA:bsf2rat) ([raw file](https://github.com/jarro2783/cxxopts/blob/fe78ff39fbb26ec248a7daf1ab3e3fb9d6babb4b/include/cxxopts.hpp#L321)):*
> ```cpp
>     public:
>     option_exists_error(const std::string& option)
>     : OptionSpecException(u8"Option '" + option + u8"' already exists")
> ```

I would prefer to make these conditional on platforms that aren't sane.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jarro2783/cxxopts/35)*

**Comment by jarro2783** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jarro2783/cxxopts/35)*

**Comment by Anton-V-K** [comment]
Any chances these changes will soon be merged into the base branch?

**Comment by jarro2783** [comment]
As I said in my comment, I like the curly quotes, as do a lot of unix tools (GCC). I would be happy to disable them with an `#ifdef`.

**Comment by jarro2783** [comment]
Fixed by #68.

**Pull request closed without merging**
