### PR TITLE
add . as valid option names

### PR DESCRIPTION
**Pull request by ryanleary**
This simply allows '.' to exist in arguments. Some libraries use `.` to denote nested configurations which is not currently possible with cxxopts. 

- - -
This change is [Reviewable](https://reviewable.io/reviews/jarro2783/cxxopts/358)

### CODE REVIEW

**Comment by jarro2783** [comment]
Can you add a test case for this?

**Comment by ryanleary** [comment]
Test added, thanks!

**Comment by jarro2783** [comment]
Looks good, can you rebase?

**Comment by ryanleary** [comment]
Rebased on latest master

**Pull request merged**
