### PR TITLE
Added const to argv type for better interoperability.

### PR DESCRIPTION
**Pull request by jgonzalezdr**
This change is [Reviewable](https://reviewable.io/reviews/jarro2783/cxxopts/99)

### CODE REVIEW

**Comment by jarro2783** [comment]
The same comment as for #98, you don't want to modify `catch.hpp`.

**Comment by jgonzalezdr** [comment]
Fixed.

**Comment by SylvainCorlay** [comment]
@jarro2783 I just wanted to give a heads up that this was a backward incompatible change between `2.1.0` and `2.1.1`.

We were passing a `const char**` to `parse`, and met compilation errors when we updated to `2.1.1`.

(Turns out that 2.1.0 that was packaged for conda right when if got released and 2.1.1 much later, which is why we only encounter the issue today.)

**Comment by SylvainCorlay** [comment]
Seems related to #123. For now, we are const-casting in xeus-cling to work around the issue.

**Comment by jarro2783** [comment]
Yeah I reverted this for `2.1.1` because `2.1.0` was broken for more people. I'm planning on adding a separate `const` interface because there is no one size fits all.

**Comment by SylvainCorlay** [comment]
Actually, const casting also makes it incompatible with `2.1.0` 

(`error: invalid conversion from ‘char**’ to ‘const char**`)

So these two versions are apparently mutually exclusive.

**Comment by SylvainCorlay** [comment]
(basically I am assuming that 2.1.1 will remain the only version to not allow for `const char**`).

**Comment by SylvainCorlay** [comment]
arg, these macros were only added after 2.1.1.

**Comment by jarro2783** [comment]
I think it would be safer to assume for now that `2.1.0` is broken and that the constness will be fixed at some point.

**Comment by SylvainCorlay** [comment]
Thanks. I now require `>=2.1.1,<3` and do the const cast.

**Pull request merged**
